In [1]:
import numpy as np

In [2]:
from aeon.datasets import load_italy_power_demand
X, y = load_italy_power_demand(return_type='numpy2d')

In [3]:
from splitter import get_parameter_value, get_candidate_splitter
distances = get_parameter_value(X)
distances

[{'euclidean': {}},
 {'dtw': {'window': 0.223}},
 {'ddtw': {'window': 0.128}},
 {'wdtw': {'g': 0.327}},
 {'wddtw': {'g': 0.206}},
 {'erp': {'g': 0.963}},
 {'lcss': {'epsilon': 0.398, 'window': 0.15}},
 {'twe': {'lmbda': 8, 'nu': 0.01}},
 {'msm': {'c': 0.01}}]

In [4]:
splitter = get_candidate_splitter(X,y,distances)
splitter

[[{'1': array([-0.33966915, -0.78271587, -1.1371532 , -1.5802    , -1.5802    ,
          -1.4915906 , -1.0485439 , -0.78271587, -0.11814579,  0.0590729 ,
           0.67933831,  0.72364299,  0.76794766,  0.19198691,  0.01476823,
          -0.20675514, -0.20675514,  0.45781494,  1.8755644 ,  1.9198691 ,
           1.4768224 ,  0.81225233,  0.28059626,  0.01476823])},
  {'2': array([-0.37357907, -0.98663192, -1.4464215 , -1.6763164 , -1.752948  ,
          -1.3697899 , -0.91000031, -0.98663192, -0.22031586,  0.85252662,
           1.0057898 ,  1.3123162 ,  1.2356846 ,  0.77589501,  0.46936859,
           0.77589501,  0.92915822,  0.39273699,  0.16284217,  0.00957896,
          -0.37357907,  1.3123162 ,  0.92915822, -0.06705265])}],
 {'euclidean': {}}]

In [5]:
X[0]

array([-0.71051757, -1.1833204 , -1.3724416 , -1.5930829 , -1.4670021 ,
       -1.3724416 , -1.0887599 ,  0.04596695,  0.92853223,  1.0861332 ,
        1.2752543 ,  0.96005242,  0.61333034,  0.01444676, -0.6474772 ,
       -0.26923494, -0.20619456,  0.61333034,  1.3698149 ,  1.4643754 ,
        1.054613  ,  0.58181015,  0.1720477 , -0.26923494])

In [6]:
type(y[0])

numpy.str_

In [7]:
np.unique(y)

array(['1', '2'], dtype='<U1')

In [8]:
X.shape

(1096, 24)

In [9]:
y

array(['1', '1', '2', ..., '2', '2', '2'], dtype='<U1')

In [10]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_labels = label_encoder.fit_transform(y)
y_labels

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [11]:
np.unique(y_labels)

array([0, 1], dtype=int64)

In [12]:
new_y = label_encoder.inverse_transform(y_labels)
print(new_y==y)

[ True  True  True ...  True  True  True]


In [13]:
X_sample = X[:3]
y_sample = y_labels[:3].reshape(-1,1)
X_combined = np.concatenate([X_sample, y_sample], axis=1)
X_combined.shape

(3, 25)

In [14]:
# Cobining the data with it's labels
X_combined = np.concatenate([X,y_labels.reshape(-1,1)], axis=1)
X_combined.shape

(1096, 25)

In [15]:
y_labels.shape

(1096,)

In [16]:
for label in np.unique(y_labels):
    print(label)

0
1


In [19]:
exemplars = []
for label in np.unique(y):
    y_new = y[y==label]
    X_new = X[y==label]
    n = np.random.randint(0,X_new.shape[0])
    exemplars.append({y_new[n]: X_new[n,:]})
    print(X_new.shape)
exemplars

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1096

In [ ]:
y[:10]

In [ ]:
import numpy as np

# Example data (ensure X and y have matching first dimensions)
X = np.random.rand(1096, 24)
y = np.random.choice(['label1', 'label2', 'label3'], 1096)

# Check dimensions
print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

# Apply masking based on unique labels in y
for label in np.unique(y):
    X_new = X[y == label]
    print(f"Shape for label '{label}': {X_new.shape}")
