In [1]:
from aeon.classification.distance_based import ProximityTree, ProximityForest
from aeon.datasets import  load_osuleaf

X, y = load_osuleaf(split='TEST', return_type='numpy3d')
X_test, y_test = load_osuleaf(split='TRAIN', return_type='numpy3d')

D:\Python\Project\Aeon\aeon\aeon\base\__init__.py:24: FutureWarning: The aeon package will soon be releasing v1.0.0 with the removal of legacy modules and interfaces such as BaseTransformer and BaseForecaster. This will contain breaking changes. See aeon-toolkit.org for more information. Set aeon.AEON_DEPRECATION_WARNING or the AEON_DEPRECATION_WARNING environmental variable to 'False' to disable this warning.
  warnings.warn(


In [2]:
import numpy as np
np.unique(y)

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [3]:
X.shape

(242, 1, 427)

In [4]:
tree = ProximityTree(max_depth = 2)
tree.fit(X, y)

ProximityTree(max_depth=2)

In [5]:
tree.classes_

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [6]:
list(tree.classes_)

['1', '2', '3', '4', '5', '6']

In [7]:
tree.n_classes_

6

In [8]:
from sklearn.metrics import accuracy_score

y_pred = tree.predict(X)
accuracy_score(y_pred, y)

0.6983471074380165

In [9]:
y_proba = tree.predict_proba(X_test)
y_proba[:40]

array([[0.        , 0.2       , 0.2       , 0.3       , 0.2       ,
        0.1       ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.86666667, 0.        , 0.13333333, 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.5       , 0.        , 0.        , 0.16666667,
        0.33333333],
       [0.25      , 0.        , 0.25      , 0.        , 0.5       ,
        0.        ],
       [0.5       , 0.        , 0.25      , 0.        , 0.25      ,
        0.        ],
       [0.27272727, 0.        , 0.72727273, 0.        , 0.        ,
        0.        ],
       [0.        , 0.19047619, 0.28571429, 0.14285714, 0.        ,
        0.38095238],
       [0.        , 0.125     , 0.25      , 0.125     , 0.5       ,
        0.        ],
       [0.27272727, 0.        , 0.72727273, 0.        , 0.        ,
        0.        ],
       [0.        , 0

In [10]:
proba=tree.predict_proba(X)
proba[:40]

array([[0.        , 0.        , 0.06666667, 0.06666667, 0.86666667,
        0.        ],
       [0.        , 0.875     , 0.        , 0.125     , 0.        ,
        0.        ],
       [0.        , 0.19047619, 0.28571429, 0.14285714, 0.        ,
        0.38095238],
       [0.        , 0.84615385, 0.        , 0.        , 0.07692308,
        0.07692308],
       [0.        , 0.5       , 0.        , 0.        , 0.16666667,
        0.33333333],
       [0.27272727, 0.        , 0.72727273, 0.        , 0.        ,
        0.        ],
       [0.        , 0.19047619, 0.28571429, 0.14285714, 0.        ,
        0.38095238],
       [0.        , 0.84615385, 0.        , 0.        , 0.07692308,
        0.07692308],
       [0.        , 0.5       , 0.        , 0.        , 0.16666667,
        0.33333333],
       [0.        , 0.1       , 0.2       , 0.5       , 0.        ,
        0.2       ],
       [0.75      , 0.        , 0.25      , 0.        , 0.        ,
        0.        ],
       [0.        , 0

In [13]:
forest = ProximityForest(max_depth=2, n_jobs=-1, n_trees=25)

In [14]:
forest.fit(X,y)

ProximityForest(max_depth=2, n_jobs=-1, n_trees=25)

In [15]:
y_pred = forest.predict(X_test)
accuracy_score(y_pred, y_test)

0.81

In [16]:
y_proba = forest.predict_proba(X_test)
y_proba[:40]

array([[0.00363636, 0.28503528, 0.17143413, 0.34263909, 0.12711867,
        0.07013647],
       [0.40660386, 0.0516293 , 0.19473814, 0.05407082, 0.29295788,
        0.        ],
       [0.        , 0.64255974, 0.06642039, 0.20319213, 0.02152305,
        0.06630469],
       [0.88481624, 0.01      , 0.04079264, 0.        , 0.06439112,
        0.        ],
       [0.1197316 , 0.11391642, 0.14932356, 0.21045162, 0.30468136,
        0.10189544],
       [0.10533333, 0.04420358, 0.32282529, 0.11323911, 0.23404551,
        0.18035318],
       [0.02292669, 0.55723555, 0.05486614, 0.07587302, 0.25249428,
        0.03660433],
       [0.25958378, 0.01      , 0.53779588, 0.06      , 0.13262034,
        0.        ],
       [0.        , 0.50636083, 0.0440214 , 0.35045294, 0.0357852 ,
        0.06337963],
       [0.10533836, 0.03593838, 0.1346931 , 0.04444444, 0.65091345,
        0.02867227],
       [0.88916332, 0.        , 0.09709309, 0.        , 0.01374359,
        0.        ],
       [0.        , 0

In [21]:
forest2 = ProximityForest(n_trees=50, n_jobs=-1)

In [22]:
forest2.fit(X,y)

ProximityForest(n_jobs=-1, n_trees=50)

In [23]:
y_proba = forest2.predict_proba(X_test)
y_proba[:40]

array([[0.  , 0.33, 0.07, 0.22, 0.15, 0.23],
       [0.24, 0.05, 0.29, 0.  , 0.42, 0.  ],
       [0.  , 0.86, 0.02, 0.07, 0.  , 0.05],
       [0.88, 0.02, 0.04, 0.  , 0.06, 0.  ],
       [0.07, 0.07, 0.4 , 0.06, 0.33, 0.07],
       [0.1 , 0.01, 0.23, 0.1 , 0.32, 0.24],
       [0.01, 0.71, 0.04, 0.04, 0.13, 0.07],
       [0.04, 0.03, 0.79, 0.01, 0.13, 0.  ],
       [0.  , 0.51, 0.  , 0.46, 0.  , 0.03],
       [0.06, 0.02, 0.2 , 0.02, 0.68, 0.02],
       [0.91, 0.  , 0.07, 0.  , 0.02, 0.  ],
       [0.  , 0.62, 0.06, 0.26, 0.  , 0.06],
       [0.34, 0.04, 0.52, 0.  , 0.09, 0.01],
       [0.  , 0.  , 0.04, 0.  , 0.92, 0.04],
       [0.  , 0.98, 0.  , 0.02, 0.  , 0.  ],
       [0.03, 0.55, 0.03, 0.14, 0.24, 0.01],
       [0.  , 0.81, 0.  , 0.12, 0.  , 0.07],
       [0.  , 0.27, 0.08, 0.5 , 0.03, 0.12],
       [0.  , 0.02, 0.01, 0.9 , 0.03, 0.04],
       [0.38, 0.05, 0.17, 0.17, 0.22, 0.01],
       [0.  , 0.1 , 0.22, 0.08, 0.53, 0.07],
       [0.  , 0.1 , 0.03, 0.85, 0.02, 0.  ],
       [0.

In [24]:
y_pred = forest2.predict(X_test)
accuracy_score(y_test, y_pred)

0.89

In [25]:
for tree in forest2.trees_:
    print('--------------------')
    print(tree.predict(X_test)[:10])

--------------------
['6' '1' '2' '1' '1' '3' '2' '3' '4' '5']
--------------------
['4' '5' '2' '1' '3' '3' '2' '5' '4' '5']
--------------------
['2' '1' '4' '1' '5' '5' '2' '3' '2' '5']
--------------------
['2' '3' '2' '1' '6' '3' '2' '3' '4' '5']
--------------------
['2' '5' '2' '1' '3' '6' '2' '2' '4' '3']
--------------------
['4' '3' '2' '1' '5' '5' '5' '3' '2' '5']
--------------------
['4' '3' '2' '1' '3' '6' '2' '3' '2' '5']
--------------------
['4' '5' '2' '5' '5' '5' '2' '3' '4' '5']
--------------------
['2' '3' '2' '1' '5' '3' '6' '3' '2' '5']
--------------------
['2' '2' '2' '1' '3' '1' '2' '3' '4' '5']
--------------------
['6' '1' '4' '1' '3' '3' '5' '3' '4' '5']
--------------------
['4' '2' '2' '2' '2' '6' '2' '3' '4' '5']
--------------------
['2' '5' '2' '1' '5' '5' '2' '3' '2' '5']
--------------------
['4' '3' '2' '1' '3' '6' '2' '3' '4' '5']
--------------------
['5' '3' '6' '1' '4' '1' '2' '3' '4' '5']
--------------------
['3' '1' '2' '1' '5' '5' '5' '5' '